package com.heima.model;

import java.io.Serializable;
import java.util.Date;

public class WkbTaskdetailuser implements Serializable {
    public  WkbTaskdetailuser()
    {
        this.tIsread=(byte)0;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetailuser.id
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetailuser.t_id
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetailuser.t_did
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    private Integer tDid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetailuser.u_id
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetailuser.t_isread
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    private Byte tIsread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetailuser.readdate
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    private Date readdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetailuser.t_perfm
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    private Byte tPerfm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetailuser.perfmdate
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    private Date perfmdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetailuser.t_srflag
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    private Byte tSrflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetailuser.srdate
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    private Date srdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetailuser.id
     *
     * @return the value of dbo.wkb_taskdetailuser.id
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetailuser.id
     *
     * @param id the value for dbo.wkb_taskdetailuser.id
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetailuser.t_id
     *
     * @return the value of dbo.wkb_taskdetailuser.t_id
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetailuser.t_id
     *
     * @param tId the value for dbo.wkb_taskdetailuser.t_id
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetailuser.t_did
     *
     * @return the value of dbo.wkb_taskdetailuser.t_did
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public Integer gettDid() {
        return tDid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetailuser.t_did
     *
     * @param tDid the value for dbo.wkb_taskdetailuser.t_did
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public void settDid(Integer tDid) {
        this.tDid = tDid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetailuser.u_id
     *
     * @return the value of dbo.wkb_taskdetailuser.u_id
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetailuser.u_id
     *
     * @param uId the value for dbo.wkb_taskdetailuser.u_id
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetailuser.t_isread
     *
     * @return the value of dbo.wkb_taskdetailuser.t_isread
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public Byte gettIsread() {
        return tIsread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetailuser.t_isread
     *
     * @param tIsread the value for dbo.wkb_taskdetailuser.t_isread
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public void settIsread(Byte tIsread) {
        this.tIsread = tIsread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetailuser.readdate
     *
     * @return the value of dbo.wkb_taskdetailuser.readdate
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public Date getReaddate() {
        return readdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetailuser.readdate
     *
     * @param readdate the value for dbo.wkb_taskdetailuser.readdate
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public void setReaddate(Date readdate) {
        this.readdate = readdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetailuser.t_perfm
     *
     * @return the value of dbo.wkb_taskdetailuser.t_perfm
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public Byte gettPerfm() {
        return tPerfm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetailuser.t_perfm
     *
     * @param tPerfm the value for dbo.wkb_taskdetailuser.t_perfm
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public void settPerfm(Byte tPerfm) {
        this.tPerfm = tPerfm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetailuser.perfmdate
     *
     * @return the value of dbo.wkb_taskdetailuser.perfmdate
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public Date getPerfmdate() {
        return perfmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetailuser.perfmdate
     *
     * @param perfmdate the value for dbo.wkb_taskdetailuser.perfmdate
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public void setPerfmdate(Date perfmdate) {
        this.perfmdate = perfmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetailuser.t_srflag
     *
     * @return the value of dbo.wkb_taskdetailuser.t_srflag
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public Byte gettSrflag() {
        return tSrflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetailuser.t_srflag
     *
     * @param tSrflag the value for dbo.wkb_taskdetailuser.t_srflag
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public void settSrflag(Byte tSrflag) {
        this.tSrflag = tSrflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetailuser.srdate
     *
     * @return the value of dbo.wkb_taskdetailuser.srdate
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public Date getSrdate() {
        return srdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetailuser.srdate
     *
     * @param srdate the value for dbo.wkb_taskdetailuser.srdate
     *
     * @mbggenerated Wed Apr 16 20:33:36 CST 2014
     */
    public void setSrdate(Date srdate) {
        this.srdate = srdate;
    }
}