package com.heima.model;

import java.io.InputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WkbTask implements Serializable {
    public WkbTask()
    {
        this.wkbTaskfileList=new ArrayList<WkbTaskfile>();
        this.wkbTaskuserList=new ArrayList<WkbTaskuser>();
        this.tDel=(byte)0;
        this.tIscomplete=(byte)0;
        this.tIsimportt=(byte)0;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_task.id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_task.t_name
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private String tName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_task.t_text
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private String tText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_task.t_voicepath
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private String tVoicepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_task.t_voicesize
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Integer tVoicesize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_task.t_voicetime
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Integer tVoicetime;

    public Integer gettVoiceid() {
        return tVoiceid;
    }

    public void settVoiceid(Integer tVoiceid) {
        this.tVoiceid = tVoiceid;
    }

    private Integer tVoiceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_task.u_id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_task.t_srflag
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Byte tSrflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_task.t_isimportt
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Byte tIsimportt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_task.t_isread
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Byte tIsread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_task.t_iscomplete
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Byte tIscomplete;

    private Date completedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_task.creator
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_task.crtdatetime
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Date crtdatetime;

    public Date getCompletedate() {
        return completedate;
    }

    public void setCompletedate(Date completedate) {
        this.completedate = completedate;
    }

    public Byte gettDel() {
        return tDel;
    }

    public void settDel(Byte tDel) {
        this.tDel = tDel;
    }

    public Date getDeldate() {
        return deldate;
    }

    public void setDeldate(Date deldate) {
        this.deldate = deldate;
    }

    private Byte tDel;

    private Date deldate;

    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_task.t_voice
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private InputStream tVoice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_task.id
     *
     * @return the value of dbo.wkb_task.id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_task.id
     *
     * @param id the value for dbo.wkb_task.id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_task.t_name
     *
     * @return the value of dbo.wkb_task.t_name
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_task.t_name
     *
     * @param tName the value for dbo.wkb_task.t_name
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_task.t_text
     *
     * @return the value of dbo.wkb_task.t_text
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public String gettText() {
        return tText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_task.t_text
     *
     * @param tText the value for dbo.wkb_task.t_text
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settText(String tText) {
        this.tText = tText == null ? null : tText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_task.t_voicepath
     *
     * @return the value of dbo.wkb_task.t_voicepath
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public String gettVoicepath() {
        return tVoicepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_task.t_voicepath
     *
     * @param tVoicepath the value for dbo.wkb_task.t_voicepath
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settVoicepath(String tVoicepath) {
        this.tVoicepath = tVoicepath == null ? null : tVoicepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_task.t_voicesize
     *
     * @return the value of dbo.wkb_task.t_voicesize
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Integer gettVoicesize() {
        return tVoicesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_task.t_voicesize
     *
     * @param tVoicesize the value for dbo.wkb_task.t_voicesize
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settVoicesize(Integer tVoicesize) {
        this.tVoicesize = tVoicesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_task.t_voicetime
     *
     * @return the value of dbo.wkb_task.t_voicetime
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Integer gettVoicetime() {
        return tVoicetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_task.t_voicetime
     *
     * @param tVoicetime the value for dbo.wkb_task.t_voicetime
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settVoicetime(Integer tVoicetime) {
        this.tVoicetime = tVoicetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_task.u_id
     *
     * @return the value of dbo.wkb_task.u_id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_task.u_id
     *
     * @param uId the value for dbo.wkb_task.u_id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_task.t_srflag
     *
     * @return the value of dbo.wkb_task.t_srflag
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Byte gettSrflag() {
        return tSrflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_task.t_srflag
     *
     * @param tSrflag the value for dbo.wkb_task.t_srflag
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settSrflag(Byte tSrflag) {
        this.tSrflag = tSrflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_task.t_isimportt
     *
     * @return the value of dbo.wkb_task.t_isimportt
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Byte gettIsimportt() {
        return tIsimportt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_task.t_isimportt
     *
     * @param tIsimportt the value for dbo.wkb_task.t_isimportt
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settIsimportt(Byte tIsimportt) {
        this.tIsimportt = tIsimportt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_task.t_isread
     *
     * @return the value of dbo.wkb_task.t_isread
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Byte gettIsread() {
        return tIsread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_task.t_isread
     *
     * @param tIsread the value for dbo.wkb_task.t_isread
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settIsread(Byte tIsread) {
        this.tIsread = tIsread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_task.t_iscomplete
     *
     * @return the value of dbo.wkb_task.t_iscomplete
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Byte gettIscomplete() {
        return tIscomplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_task.t_iscomplete
     *
     * @param tIscomplete the value for dbo.wkb_task.t_iscomplete
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settIscomplete(Byte tIscomplete) {
        this.tIscomplete = tIscomplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_task.creator
     *
     * @return the value of dbo.wkb_task.creator
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_task.creator
     *
     * @param creator the value for dbo.wkb_task.creator
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_task.crtdatetime
     *
     * @return the value of dbo.wkb_task.crtdatetime
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Date getCrtdatetime() {
        return crtdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_task.crtdatetime
     *
     * @param crtdatetime the value for dbo.wkb_task.crtdatetime
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void setCrtdatetime(Date crtdatetime) {
        this.crtdatetime = crtdatetime;
    }

    public Date getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_task.t_voice
     *
     * @return the value of dbo.wkb_task.t_voice
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public InputStream gettVoice() {
        return tVoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_task.t_voice
     *
     * @param tVoice the value for dbo.wkb_task.t_voice
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settVoice(InputStream tVoice) {
        this.tVoice = tVoice;
    }

    public List<WkbTaskfile> getWkbTaskfileList() {
        return wkbTaskfileList;
    }

    public void setWkbTaskfileList(List<WkbTaskfile> wkbTaskfileList) {
        this.wkbTaskfileList = wkbTaskfileList;
    }

    public List<WkbTaskuser> getWkbTaskuserList() {
        return wkbTaskuserList;
    }

    public void setWkbTaskuserList(List<WkbTaskuser> wkbTaskuserList) {
        this.wkbTaskuserList = wkbTaskuserList;
    }

    private List<WkbTaskfile> wkbTaskfileList;
    private List<WkbTaskuser> wkbTaskuserList;
}