package com.heima.model;

import java.io.InputStream;
import java.io.Serializable;
import java.util.Date;

public class WkbTaskfile implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskfile.id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskfile.t_id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskfile.t_did
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Integer tDid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskfile.t_filename
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private String tFilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskfile.t_filetype
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private String tFiletype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskfile.t_filesize
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Integer tFilesize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskfile.t_filepath
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private String tFilepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskfile.creator
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskfile.crtdatetime
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Date crtdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskfile.t_file
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private InputStream tFile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskfile.id
     *
     * @return the value of dbo.wkb_taskfile.id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskfile.id
     *
     * @param id the value for dbo.wkb_taskfile.id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskfile.t_id
     *
     * @return the value of dbo.wkb_taskfile.t_id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskfile.t_id
     *
     * @param tId the value for dbo.wkb_taskfile.t_id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskfile.t_did
     *
     * @return the value of dbo.wkb_taskfile.t_did
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Integer gettDid() {
        return tDid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskfile.t_did
     *
     * @param tDid the value for dbo.wkb_taskfile.t_did
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settDid(Integer tDid) {
        this.tDid = tDid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskfile.t_filename
     *
     * @return the value of dbo.wkb_taskfile.t_filename
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public String gettFilename() {
        return tFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskfile.t_filename
     *
     * @param tFilename the value for dbo.wkb_taskfile.t_filename
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settFilename(String tFilename) {
        this.tFilename = tFilename == null ? null : tFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskfile.t_filetype
     *
     * @return the value of dbo.wkb_taskfile.t_filetype
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public String gettFiletype() {
        return tFiletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskfile.t_filetype
     *
     * @param tFiletype the value for dbo.wkb_taskfile.t_filetype
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settFiletype(String tFiletype) {
        this.tFiletype = tFiletype == null ? null : tFiletype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskfile.t_filesize
     *
     * @return the value of dbo.wkb_taskfile.t_filesize
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Integer gettFilesize() {
        return tFilesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskfile.t_filesize
     *
     * @param tFilesize the value for dbo.wkb_taskfile.t_filesize
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settFilesize(Integer tFilesize) {
        this.tFilesize = tFilesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskfile.t_filepath
     *
     * @return the value of dbo.wkb_taskfile.t_filepath
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public String gettFilepath() {
        return tFilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskfile.t_filepath
     *
     * @param tFilepath the value for dbo.wkb_taskfile.t_filepath
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settFilepath(String tFilepath) {
        this.tFilepath = tFilepath == null ? null : tFilepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskfile.creator
     *
     * @return the value of dbo.wkb_taskfile.creator
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskfile.creator
     *
     * @param creator the value for dbo.wkb_taskfile.creator
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskfile.crtdatetime
     *
     * @return the value of dbo.wkb_taskfile.crtdatetime
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Date getCrtdatetime() {
        return crtdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskfile.crtdatetime
     *
     * @param crtdatetime the value for dbo.wkb_taskfile.crtdatetime
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void setCrtdatetime(Date crtdatetime) {
        this.crtdatetime = crtdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskfile.t_file
     *
     * @return the value of dbo.wkb_taskfile.t_file
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public InputStream gettFile() {
        return tFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskfile.t_file
     *
     * @param tFile the value for dbo.wkb_taskfile.t_file
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settFile(InputStream tFile) {
        this.tFile = tFile;
    }
}