package com.heima.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Created with (TC).
 * User: 徐志凯
 * Date: 14-4-10
 * 橡果国际-系统集成部
 * Copyright (c) 2012-2013 ACORN, Inc. All rights reserved.
 */
public class WkbFriends implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_friends.id
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_friends.u_id
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_friends.f_uid
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    private Integer fUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_friends.f_nickname
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    private String fNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_friends.g_id
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    private Integer gId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_friends.m_share
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    private Byte mShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_friends.s_share
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    private Byte sShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_friends.s_sharetype
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    private Byte sSharetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_friends.creator
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_friends.crtdatetime
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    private Date crtdatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_friends.id
     *
     * @return the value of dbo.wkb_friends.id
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_friends.id
     *
     * @param id the value for dbo.wkb_friends.id
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_friends.u_id
     *
     * @return the value of dbo.wkb_friends.u_id
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_friends.u_id
     *
     * @param uId the value for dbo.wkb_friends.u_id
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_friends.f_uid
     *
     * @return the value of dbo.wkb_friends.f_uid
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public Integer getfUid() {
        return fUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_friends.f_uid
     *
     * @param fUid the value for dbo.wkb_friends.f_uid
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public void setfUid(Integer fUid) {
        this.fUid = fUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_friends.f_nickname
     *
     * @return the value of dbo.wkb_friends.f_nickname
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public String getfNickname() {
        return fNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_friends.f_nickname
     *
     * @param fNickname the value for dbo.wkb_friends.f_nickname
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public void setfNickname(String fNickname) {
        this.fNickname = fNickname == null ? null : fNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_friends.g_id
     *
     * @return the value of dbo.wkb_friends.g_id
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public Integer getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_friends.g_id
     *
     * @param gId the value for dbo.wkb_friends.g_id
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public void setgId(Integer gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_friends.m_share
     *
     * @return the value of dbo.wkb_friends.m_share
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public Byte getmShare() {
        return mShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_friends.m_share
     *
     * @param mShare the value for dbo.wkb_friends.m_share
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public void setmShare(Byte mShare) {
        this.mShare = mShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_friends.s_share
     *
     * @return the value of dbo.wkb_friends.s_share
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public Byte getsShare() {
        return sShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_friends.s_share
     *
     * @param sShare the value for dbo.wkb_friends.s_share
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public void setsShare(Byte sShare) {
        this.sShare = sShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_friends.s_sharetype
     *
     * @return the value of dbo.wkb_friends.s_sharetype
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public Byte getsSharetype() {
        return sSharetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_friends.s_sharetype
     *
     * @param sSharetype the value for dbo.wkb_friends.s_sharetype
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public void setsSharetype(Byte sSharetype) {
        this.sSharetype = sSharetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_friends.creator
     *
     * @return the value of dbo.wkb_friends.creator
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_friends.creator
     *
     * @param creator the value for dbo.wkb_friends.creator
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_friends.crtdatetime
     *
     * @return the value of dbo.wkb_friends.crtdatetime
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public Date getCrtdatetime() {
        return crtdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_friends.crtdatetime
     *
     * @param crtdatetime the value for dbo.wkb_friends.crtdatetime
     *
     * @mbggenerated Thu Apr 10 12:42:56 CST 2014
     */
    public void setCrtdatetime(Date crtdatetime) {
        this.crtdatetime = crtdatetime;
    }
}
