package com.heima.model;

import java.io.Serializable;

/**
 * Created with (TC).
 * User: 徐志凯
 * Date: 14-4-8
 * 橡果国际-系统集成部
 * Copyright (c) 2012-2013 ACORN, Inc. All rights reserved.
 */
public class WkbSeq implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_seq.id_name
     *
     * @mbggenerated Tue Apr 08 19:55:23 CST 2014
     */
    private String idName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_seq.id_seq
     *
     * @mbggenerated Tue Apr 08 19:55:23 CST 2014
     */
    private Integer idSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_seq.id_dsc
     *
     * @mbggenerated Tue Apr 08 19:55:23 CST 2014
     */
    private String idDsc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_seq.id_name
     *
     * @return the value of dbo.wkb_seq.id_name
     *
     * @mbggenerated Tue Apr 08 19:55:23 CST 2014
     */
    public String getIdName() {
        return idName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_seq.id_name
     *
     * @param idName the value for dbo.wkb_seq.id_name
     *
     * @mbggenerated Tue Apr 08 19:55:23 CST 2014
     */
    public void setIdName(String idName) {
        this.idName = idName == null ? null : idName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_seq.id_seq
     *
     * @return the value of dbo.wkb_seq.id_seq
     *
     * @mbggenerated Tue Apr 08 19:55:23 CST 2014
     */
    public Integer getIdSeq() {
        return idSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_seq.id_seq
     *
     * @param idSeq the value for dbo.wkb_seq.id_seq
     *
     * @mbggenerated Tue Apr 08 19:55:23 CST 2014
     */
    public void setIdSeq(Integer idSeq) {
        this.idSeq = idSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_seq.id_dsc
     *
     * @return the value of dbo.wkb_seq.id_dsc
     *
     * @mbggenerated Tue Apr 08 19:55:23 CST 2014
     */
    public String getIdDsc() {
        return idDsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_seq.id_dsc
     *
     * @param idDsc the value for dbo.wkb_seq.id_dsc
     *
     * @mbggenerated Tue Apr 08 19:55:23 CST 2014
     */
    public void setIdDsc(String idDsc) {
        this.idDsc = idDsc == null ? null : idDsc.trim();
    }
}
