package com.heima.model;

import java.io.InputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WkbTaskdetail implements Serializable {

    public WkbTaskdetail()
    {
        this.wkbTaskdetailuserList=new ArrayList<WkbTaskdetailuser>();
        this.wkbTaskfileList=new ArrayList<WkbTaskfile>();
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetail.id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetail.t_id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetail.u_id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetail.t_text
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private String tText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetail.t_voicesize
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Integer tVoicesize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetail.t_voicetime
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Integer tVoicetime;

    public Integer gettVoiceid() {
        return tVoiceid;
    }

    public void settVoiceid(Integer tVoiceid) {
        this.tVoiceid = tVoiceid;
    }

    private Integer tVoiceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetail.t_voicepath
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private String tVoicepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetail.creator
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetail.crtdatetime
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private Date crtdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.wkb_taskdetail.t_voice
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    private InputStream tVoice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetail.id
     *
     * @return the value of dbo.wkb_taskdetail.id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetail.id
     *
     * @param id the value for dbo.wkb_taskdetail.id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetail.t_id
     *
     * @return the value of dbo.wkb_taskdetail.t_id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetail.t_id
     *
     * @param tId the value for dbo.wkb_taskdetail.t_id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetail.u_id
     *
     * @return the value of dbo.wkb_taskdetail.u_id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetail.u_id
     *
     * @param uId the value for dbo.wkb_taskdetail.u_id
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetail.t_text
     *
     * @return the value of dbo.wkb_taskdetail.t_text
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public String gettText() {
        return tText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetail.t_text
     *
     * @param tText the value for dbo.wkb_taskdetail.t_text
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settText(String tText) {
        this.tText = tText == null ? null : tText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetail.t_voicesize
     *
     * @return the value of dbo.wkb_taskdetail.t_voicesize
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Integer gettVoicesize() {
        return tVoicesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetail.t_voicesize
     *
     * @param tVoicesize the value for dbo.wkb_taskdetail.t_voicesize
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settVoicesize(Integer tVoicesize) {
        this.tVoicesize = tVoicesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetail.t_voicetime
     *
     * @return the value of dbo.wkb_taskdetail.t_voicetime
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Integer gettVoicetime() {
        return tVoicetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetail.t_voicetime
     *
     * @param tVoicetime the value for dbo.wkb_taskdetail.t_voicetime
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settVoicetime(Integer tVoicetime) {
        this.tVoicetime = tVoicetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetail.t_voicepath
     *
     * @return the value of dbo.wkb_taskdetail.t_voicepath
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public String gettVoicepath() {
        return tVoicepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetail.t_voicepath
     *
     * @param tVoicepath the value for dbo.wkb_taskdetail.t_voicepath
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settVoicepath(String tVoicepath) {
        this.tVoicepath = tVoicepath == null ? null : tVoicepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetail.creator
     *
     * @return the value of dbo.wkb_taskdetail.creator
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetail.creator
     *
     * @param creator the value for dbo.wkb_taskdetail.creator
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetail.crtdatetime
     *
     * @return the value of dbo.wkb_taskdetail.crtdatetime
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public Date getCrtdatetime() {
        return crtdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetail.crtdatetime
     *
     * @param crtdatetime the value for dbo.wkb_taskdetail.crtdatetime
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void setCrtdatetime(Date crtdatetime) {
        this.crtdatetime = crtdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.wkb_taskdetail.t_voice
     *
     * @return the value of dbo.wkb_taskdetail.t_voice
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public InputStream gettVoice() {
        return tVoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.wkb_taskdetail.t_voice
     *
     * @param tVoice the value for dbo.wkb_taskdetail.t_voice
     *
     * @mbggenerated Tue Apr 15 22:15:28 CST 2014
     */
    public void settVoice(InputStream tVoice) {
        this.tVoice = tVoice;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        WkbTaskdetail that = (WkbTaskdetail) o;

        if (id != null ? !id.equals(that.id) : that.id != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }

    public List<WkbTaskdetailuser> getWkbTaskdetailuserList() {
        return wkbTaskdetailuserList;
    }

    public void setWkbTaskdetailuserList(List<WkbTaskdetailuser> wkbTaskdetailuserList) {
        this.wkbTaskdetailuserList = wkbTaskdetailuserList;
    }

    private List<WkbTaskdetailuser> wkbTaskdetailuserList;

    public List<WkbTaskfile> getWkbTaskfileList() {
        return wkbTaskfileList;
    }

    public void setWkbTaskfileList(List<WkbTaskfile> wkbTaskfileList) {
        this.wkbTaskfileList = wkbTaskfileList;
    }

    private List<WkbTaskfile> wkbTaskfileList;
}